website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.secret_key ='key_123'

    from .views import views

    app.register_blueprint(views, url_prefix='/')

    return app

website/views.py
from flask import Blueprint, render_template, request, send_file, redirect, url_for

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/ats')
def ats():
    return render_template('ats.html')

# NLP Stuff
from nlp import modify_des

@views.route('/generate_resume', methods=['POST'])
def gen_res():
    con = request.form.get('context_description')

    # Get basic information
    basic_info = {
        'Full Name': request.form.get('full_name'),
        'Email': request.form.get('email'),
        'Mobile Number': request.form.get('mobile_number'),
        'Gender': request.form.get('gender'),
        'Website': request.form.get('website'),
        'Objective': request.form.get('objective')
    }

    # Educational Details
    educational_details = []
    for i in range(1, 5):
        qualification = request.form.get(f'qualification{i}')
        degree = request.form.get(f'degree{i}')
        institution_name = request.form.get(f'institution_name{i}')
        from_till = request.form.get(f'from_till{i}')
        gpa = request.form.get(f'gpa{i}')
        coursework = request.form.get(f'coursework{i}')

        if degree:
            educational_details.append({
                f'Qualification {i}': qualification,
                'Degree': degree,
                'Institution Name': institution_name,
                'From - Till': from_till,
                'GPA': gpa,
                'Coursework': coursework
            })

    # Skills
    technical_skills = request.form.get('technical_skills').split(', ')
    technical_proficiency = request.form.get('technical_proficiency').split(', ')
    soft_skills = request.form.get('soft_skills').split(',')
    soft_proficiency = request.form.get('soft_proficiency').split(',')

    technical_dict = dict(zip(technical_skills, technical_proficiency))
    soft_dict = dict(zip(soft_skills, soft_proficiency))

    # Work Experience
    work_experience = []
    for i in range(1, 4):
        role_name = request.form.get(f'role_name{i}')
        company_name_location = request.form.get(f'company_name_location{i}')
        work_from_till = request.form.get(f'work_from_till{i}')
        achievements = request.form.get(f'achievements{i}')

        if role_name:
            work_experience.append({
                'Role Name': role_name,
                'Company Name - Location': company_name_location,
                'Work From - Till': work_from_till,
                'Achievements': modify_des(con, achievements, 'wex')
            })

    # Projects
    projects = []
    for i in range(1, 4):
        project_title = request.form.get(f'project_title{i}')
        tech_stack = request.form.get(f'tech_stack{i}')
        project_description = request.form.get(f'project_description{i}')

        if project_title:
            projects.append({
                'Project Title': project_title,
                'Tech Stack': tech_stack,
                'Project Description': modify_des(con, project_description, 'proj')
            })

    # Leadership Experience
    leadership_experience = []
    for i in range(1, 4):
        leadership_description = request.form.get(f'leadership_description{i}')

        if leadership_description:
            leadership_experience.append({
                'Leadership Description': modify_des(con, leadership_description, 'lex')
            })
    
	# fill_latex_template(basic_info, educational_details, technical_skills, soft_skills, work_experience, projects, leadership_experience)
            
    try:
        # Writing data to file
        with open('website/1.txt', 'w') as file:
            # Write basic information
            file.write('Basic Information:\n')
            for key, value in basic_info.items():
                file.write(f"{key}: {value}\n")

            # Write educational details
            file.write('\nEducational Details:\n')
            for edu in educational_details:
                for key, value in edu.items():
                    file.write(f"{key}: {value}\n")
                file.write('\n')

            # Write skills
            file.write('\nSkills:\nTechnical Skills:\n')
            for skill, proficiency in technical_dict.items():
                file.write(f"{skill}: {proficiency}\n")

            file.write('\nSoft Skills:\n')
            for skill, proficiency in soft_dict.items():
                file.write(f"{skill}: {proficiency}\n")

            # Write work experience
            file.write('\nWork Experience:\n')
            for exp in work_experience:
                for key, value in exp.items():
                    file.write(f"{key}: {value}\n")
                file.write('\n')

            # Write projects
            file.write('\nProjects:\n')
            for proj in projects:
                for key, value in proj.items():
                    file.write(f"{key}: {value}\n")
                file.write('\n')

            # Write leadership experience
            file.write('\nLeadership Experience:\n')
            for leader_exp in leadership_experience:
                for key, value in leader_exp.items():
                    file.write(f"{key}: {value}\n")
                file.write('\n')
        
        return send_file('1.txt')  

    except Exception as e:
        return f"Error occurred: {str(e)}"



# ATS Compliant LaTeX templating
# def fill_latex_template(basic_info, educational_details, technical_skills, soft_skills, work_experience, projects, leadership_experience):
#     template = r"""
#     \documentclass{resume} 

#     \usepackage[left=0.4 in,top=0.4in,right=0.4 in,bottom=0.4in]{geometry} % Document margins
#     \newcommand{\tab}[1]{\hspace{.2667\textwidth}\rlap{#1}} 
#     \newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
#     \name{""" + basic_info['Full Name'] + r"} % Your name\n\n" + \
#     r"\address{" + basic_info['Mobile Number'] + r" \\ San Francisco, CA}\n" + \
#     r"\address{\href{mailto:" + basic_info['Email'] + r"}{contact@gmail.com} \\ \href{" + basic_info['Website'] + r"}{linkedin.com/} \\ \href{www..com}{www..com}}  %\n\n" + \
#     r"\begin{document}\n\n" + \
#     r"\begin{rSection}{OBJECTIVE}\n" + \
#     r"{" + basic_info['Objective'] + r"}\n" + \
#     r"\end{rSection}\n\n" + \
#     r"\begin{rSection}{Education}\n"

#     # Fill educational details
#     for i, edu in enumerate(educational_details, start=1):
#         template += r"{\bf " + edu['Degree'] + r"}, " + edu['Institution Name'] + r" \hfill {" + edu['From - Till'] + r"}\n" + \
#                     r"Relevant Coursework: " + edu['Coursework'] + r".\n\n"

#     template += r"\end{rSection}\n\n" + \
#                 r"\begin{rSection}{SKILLS}\n" + \
#                 r"\begin{tabular}{ @{} >{\bfseries}l @{\hspace{6ex}} l }\n" + \
#                 r"Technical Skills & " + ', '.join(technical_skills) + r" \\\\" + \
#                 r"Soft Skills & " + ', '.join(soft_skills) + r" \\\\\n" + \
#                 r"\end{tabular}\n" + \
#                 r"\end{rSection}\n\n" + \
#                 r"\begin{rSection}{EXPERIENCE}\n"

#     # Fill work experience
#     for exp in work_experience:
#         template += r"\textbf{" + exp['Role Name'] + r"} \hfill " + exp['Work From - Till'] + r"\n" + \
#                     exp['Company Name - Location'] + r"\n" + \
#                     r"\begin{itemize}\n" + \
#                     r"    \itemsep -3pt {}\n" + \
#                     r"    \item " + exp['Achievements'] + r"\n" + \
#                     r"\end{itemize}\n\n"

#     template += r"\end{rSection}\n\n" + \
#                 r"\begin{rSection}{PROJECTS}\n"

#     # Fill projects
#     for proj in projects:
#         template += r"\vspace{-1.25em}\n" + \
#                     r"\item \textbf{" + proj['Project Title'] + r".} " + proj['Project Description'] + r"\n"

#     template += r"\end{rSection}\n\n" + \
#                 r"\begin{rSection}{Extra-Curricular Activities}\n" + \
#                 r"\begin{itemize}\n"

#     # Fill leadership experience
#     for lead_exp in leadership_experience:
#         template += r"\item " + lead_exp['Leadership Description'] + r"\n"

#     template += r"\end{itemize}\n" + \
#                 r"\end{rSection}\n\n" + \
#                 r"\end{document}"

#     print(template)

website/templates/ats.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/form.css') }}">
    <script src="{{ url_for('static', filename='script/form.js') }}"></script> 
    <title>Resume Form</title> 

</head>

<body>
    <h2 style="font-size: xx-large;">User Details</h2>
    <form action="{{ url_for('views.gen_res') }}" method="POST">

        <!-- NLP context-->
        <fieldset id="nlp_context">
            <legend>Resume Objective (for NLP context) *</legend>
            <textarea id="context_description" name="context_description" rows="4" cols="40" required></textarea><br>
        </fieldset>

        <!-- Personal Details -->
        <fieldset>
            <legend>Personal Details</legend>
            <label for="full_name">Full Name: *</label>
            <input type="text" id="full_name" name="full_name" required><br>
            
            <label for="email">Email: *</label>
            <input type="email" id="email" name="email" required><br>
            
            <label for="mobile_number">Mobile Number: *</label>
            <input type="tel" id="mobile_number" name="mobile_number" required><br>
            
            <label for="gender">Gender: *</label>
            <select id="gender" name="gender" required>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
            </select><br>
            
            <label for="website">Website:</label>
            <input type="text" id="website" name="website"><br>
        </fieldset>

        <!-- Educational Details -->
        <fieldset id="educationFieldset">
            <legend>Educational Details</legend>

            <fieldset>
            <label for="degree">Qualification 1: *</label>
            <input type="text" id="degree1" name="degree1" required><br>
            
            <label for="institution_name">Institution Name: *</label>
            <input type="text" id="institution_name1" name="institution_name1" required><br>
            
            <label for="from_till">From - Till: *</label>
            <input type="text" id="from_till1" name="from_till1" required><br>
            
            <label for="gpa">GPA: *</label>
            <input type="text" id="gpa1" name="gpa1" required><br>
            
            <label for="coursework">Coursework: *</label>
            <input type="text" id="coursework1" name="coursework1" required><br>
            </fieldset>
        </fieldset>
        <button class="add-button" type="button" onclick="addEducation()">Add Education</button>

        <!-- Skills -->
        <fieldset>
            <legend>Skills (Comma {, } separated)</legend>
            <!-- Technical Skills -->
            <label for="technical_skills">Technical Skills: *</label>
            <input type="text" id="technical_skills" name="technical_skills" required><br>
            
            <label for="technical_proficiency">Proficiency (On an ascending scale of 10): *</label>
            <input style="margin-bottom: 5%;" type="text" id="technical_proficiency" name="technical_proficiency" required><br>
            
            <!-- Soft Skills -->
            <label for="soft_skills">Soft Skills: *</label>
            <input type="text" id="soft_skills" name="soft_skills" required><br>
            
            <label for="soft_proficiency">Proficiency (On an ascending scale of 10): *</label>
            <input type="text" id="soft_proficiency" name="soft_proficiency" required><br>   
        </fieldset>

        <!-- Work Experience -->
        <fieldset id="wexFieldset">
            <legend>Work Experience</legend>
            <fieldset>
            <label for="role_name1">Role Title 1:</label>
            <input type="text" id="role_name1" name="role_name1"><br>
            
            <label for="company_name_location1">Company Name, Location:</label>
            <input type="text" id="company_name_location1" name="company_name_location1"><br>
            
            <label for="work_from_till1">Work From - Till:</label>
            <input type="text" id="work_from_till1" name="work_from_till1"><br>
            
            <label for="achievements1">Achievements:</label>
            <textarea id="achievements1" name="achievements1" rows="4" cols="50" ></textarea><br>
            </fieldset>
        </fieldset>
        <button class="add-button" type="button" onclick="addWorkExperience()">Add Work Experience</button>

        <!-- Projects -->
        <fieldset id="projectFieldset">
            <legend>Projects</legend>
            <fieldset>
            <label for="project_title1">Project Title 1:</label>
            <input type="text" id="project_title1" name="project_title1"><br>
            
            <label for="tech_stack">Tech Stack:</label>
            <input type="text" id="tech_stack1" name="tech_stack1"><br>
            
            <label for="project_description">Project Description:</label>
            <textarea id="project_description1" name="project_description1" rows="4" cols="50"></textarea><br>
            </fieldset>
        </fieldset>
        <button class="add-button" type="button" onclick="addProject()">Add Project</button>

        <!-- Leadership Experience -->
        <fieldset id="lexFieldset">
            <legend>Leadership Experience</legend>
            
            <fieldset>
            <label for="leadership_description1">Description 1:</label>
            <textarea id="leadership_description1" name="leadership_description1" rows="4" cols="50"></textarea><br>
            </fieldset>
        </fieldset>
        <button class="add-button" type="button" onclick="addLeadershipExperience()">Add Leadership Experience</button>
        
        <br><input type="submit" value="Submit">
    </form>
</body>

</html>



website/templates/index.html
<html>

<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

  <title>Resume Builder</title>

  <link rel="stylesheet"  href="{{ url_for('static', filename='styles/bootstrap.css') }}"/>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}"/>
</head>

<body>
  
  <div class="main">

    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container">
        <a class="navbar-brand" href="">
          <span style="font-size: 50px;">
            Resume Builder
          </span>
        </a>
      </nav>
    </div>
    </header>

    <section class="slider_section">
      <div class="col-md-5 offset-md-1">
        <div class="detail-box">
          
          <h2>
            Don't know how to build your first resume? <br><br>
            <h2-2>Don't want to bother with the hassle of formatting?<br><br></h2.2>
          </h2>
          <h1>
            Get your easy ATS Friendly Resume<br>
            RIGHT NOW!
          </h1>

          <div class="btn-box">
            <a href="{{ url_for('views.ats') }}" class="btn-1">
              Get Started
            </a>
          </div>

        </div>
      </div>

      <div class="offset-md-1 col-md-4 img-container">
        <div class="img-box">
          <img src="{{ url_for('static', filename='img/slider-img.png') }}">
        </div>
      </div>

    </section>

  </div>

<section class="experience_section layout_padding" style="padding-bottom : 0px;">
  <div class="container">
    <div class="row">
      
      <div class="col-md-5">
        <div class="img-box">

          <img src="{{ url_for('static', filename='img/experience-img.jpg') }}">
        </div>
      </div>

            
            <div class="offset-md-2 col-md-5" style=" margin-right: 0px;">
              <h2 style="color : black">Upgrading Resumes with Natural Language Processing</h2>
              <p>
                Our website uses Natural Language Processing to optimize the descriptive content of resumes. NLP allows us to ensure that resume descriptions are clear, concise, and goal-oriented. We enhance the effectiveness of resumes by including proven keywords that attract the attention of both Applicant Tracking System (ATS) algorithms and recruiters. This integration of NLP ensures that resumes created through our website stand out and indeed makes it more compatible with modern hiring practices.
              </p>
            </div>
          
          </div>
        </div>
    
      
      <div class="col-md-10" style="margin:auto; margin-top: 6%;">
        <div class="detail-box">
          <div class="heading_container">
            <h2 style="color: black;">
              Your resume becomes your identity in the job world
            </h2>
          </div>
          <p>
            ATS (Applicant Tracking System) is software used by employers at almost all conglomerates, even more so at FAANG, to manage applicant screening, resume parsing, and candidate communication. The system helps streamline the hiring process by automatically filtering and organizing incoming resumes based on specific criteria set by the employer.
            <ul>
              <li>An ATS friendly resume is usually only a page long</li>
              <li>An ATS friendly resume sticks to a clean, easy-to-read layout with standard fonts and consistent formatting</li>
              <li>Tailor your resume by including relevant keywords from the job description to match the ATS filtering criteria</li>
              <li>ATS avoids graphics and images</li>
              <li>Clearly label sections such as "Work Experience," "Education," and "Skills" to help ATS categorize your information accurately</li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</section>

</body>

</html>